export const ADD_USER = 'USERS/ADD_USER';
export const DELETE_USER = 'USERS/ADD_USER';
export const FETCH_USERS_REQUEST = 'USERS/FETCH_USERS_REQUEST';
export const FETCH_USERS_RESOLVE = 'USERS/FETCH_USERS_RESOLVE';
export const FETCH_USERS_FAIL = 'USERS/FETCH_USERS_FAIL';
